import scrollSuave from "./modules/scrollSuave.js";
import sessoesAnimacao from "./modules/sessoesAnimacao.js";
import accordion from "./modules/accordion.js";
import navTab from "./modules/navTab.js";
import modal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import dropdownMenu from "./modules/dropdown-menu.js";
import menuMobile from "./modules/menuMobile.js";
import animaNumeros from "./modules/animaNumeros.js";
import horario from "./modules/horarioAbertura.js";

navTab();
accordion();
scrollSuave();
sessoesAnimacao();
modal();
initTooltip();
dropdownMenu();
menuMobile();
animaNumeros();
horario();
